#!/bin/bash

#SBATCH --partition sched_mit_raffaele
#SBATCH --nodes 1
#SBATCH --exclusive
#SBATCH --mem 64000
#SBATCH --time=48:00:00
#SBATCH --error stderr
#SBATCH --output stdout
#SBATCH --job-name transfer
#SBATCH --mail-type FAIL,END
#SBATCH --mail-user masonr@mit.edu

conda activate add_netcdf
#python get_gs.py
wget -i mask_urls.txt
